function WT_transition_figure_code(X1, Y1, Y2, X2, YMatrix1, YMatrix2)
%CREATEFIGURE(X1, Y1, Y2, X2, YMatrix1, YMatrix2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  X2:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 25-Jan-2019 16:46:34

% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Parent',subplot1,'LineWidth',2,'Color',[0 0 0]);

% Create ylabel
ylabel('MW flow','FontSize',13.2);

% Create title
title('sharp trend','FontSize',13.2);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0 60]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[60 100]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(subplot1,[-1 1]);
box(subplot1,'on');
grid(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontSize',12);
% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X1,Y2,'Parent',subplot2,'LineWidth',2,'Color',[0 0 0]);

% Create title
title('slow trend','FontSize',13.2);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0 60]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[-0.925757309269648 60]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(subplot2,[-1 1]);
box(subplot2,'on');
grid(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'FontSize',12);
% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1);
hold(subplot3,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X2,YMatrix1,'Parent',subplot3,'Color',[0 0 0]);
set(plot1(1),'DisplayName','weighted','LineWidth',3);
set(plot1(2),'DisplayName','latest','LineWidth',2,'LineStyle','--');

% Create ylabel
ylabel('Trend (MW/min)','FontSize',13.2);

% Create xlabel
xlabel('Time (minute)','FontSize',13.2);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[0 60]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[-6 3]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(subplot3,[-1 1]);
box(subplot3,'on');
grid(subplot3,'on');
% Set the remaining axes properties
set(subplot3,'FontSize',12);
% Create legend
legend1 = legend(subplot3,'show');
set(legend1,'Location','best');

% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1);
hold(subplot4,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X2,YMatrix2,'Parent',subplot4,'Color',[0 0 0]);
set(plot2(1),'DisplayName','weighted','LineWidth',3);
set(plot2(2),'DisplayName','latest','LineWidth',2,'LineStyle','--');

% Create xlabel
xlabel('Time (minute)','FontSize',13.2);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot4,[0 60]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot4,[-6 3]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(subplot4,[-1 1]);
box(subplot4,'on');
grid(subplot4,'on');
% Set the remaining axes properties
set(subplot4,'FontSize',12);
% Create legend
legend2 = legend(subplot4,'show');
set(legend2,...
    'Position',[0.748629626555657 0.12669882060725 0.140643620981221 0.076704543422569]);

% Create line
annotation(figure1,'line',[0.213349225268176 0.213349225268176],...
    [0.585227272727273 0.929924242424242],'LineWidth',1,'LineStyle','--');

% Create line
annotation(figure1,'line',[0.650774731823598 0.650774731823598],...
    [0.581439393939394 0.926136363636364],'LineWidth',1,'LineStyle','--');

